import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const local = createRequire(import.meta.url);
const bundled = createRequire(path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'));
export function dependency(name) {
  try { return local(name); } catch (error) {
    if (error.code !== 'MODULE_NOT_FOUND') throw error;
    return bundled(name);
  }
}
const { marked } = dependency('marked');
export async function generateWeb() {
  const source = await fs.readFile(path.join(root, 'resume_source.md'), 'utf8');
  const styles = await fs.readFile(path.join(root, 'templates/resume-web.css'), 'utf8');
  const tokens = marked.lexer(source);
  const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
  const name = escape(tokens.find(token => token.type === 'heading' && token.depth === 1).text);
  const sections = [];
  let current = { id: 'intro', title: '', tokens: [] };
  sections.push(current);
  for (const token of tokens) {
    if (token.type === 'heading' && token.depth === 2) {
      const id = token.text.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      current = { id, title: token.text, tokens: [] };
      sections.push(current);
    }
    current.tokens.push(token);
  }
  const renderer = new marked.Renderer();
  renderer.heading = function ({ depth, tokens, text }) {
    const split = text.lastIndexOf(' — ');
    if ((depth === 3 || depth === 4) && split >= 0) {
      return `<h${depth} class="entry-heading"><span>${marked.parseInline(text.slice(0, split))}</span><span class="separator"> — </span><span class="entry-detail">${marked.parseInline(text.slice(split + 3))}</span></h${depth}>\n`;
    }
    return `<h${depth}>${this.parser.parseInline(tokens)}</h${depth}>\n`;
  };
  const body = sections.map(({ id, tokens }, i) => i === 0
    ? `<header class="masthead" id="intro">${marked.parser(tokens, { renderer })}</header>`
    : `<section id="${id}" aria-labelledby="heading-${id}">${marked.parser(tokens, { renderer }).replace('<h2>', `<h2 id="heading-${id}">`)}</section>`).join('\n');
  // Optional section navigation retained for forks. To restore, uncomment the
  // next two lines and remove the empty navigation declaration below.
  // const nav = sections.slice(1).map(({ id, title }) => `<a href="#${id}">${title}</a>`).join('\n');
  // const navigation = `<nav aria-label="Resume sections"><span class="nav-label">On this page</span>${nav}</nav>`;
  const navigation = '';
  return `<!doctype html>
<!-- Generated from resume_source.md. Do not edit this file. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${name} — Resume</title><meta name="description" content="${name}’s public resume.">
<link rel="canonical" href="https://natek.pro/resume/"><style>${styles}</style></head>
<body><a class="skip" href="#resume">Skip to resume</a>
<div class="toolbar"><a href="/">natek.pro</a><a class="pdf-link" href="/resume-pdf/">Open PDF <span aria-hidden="true">↗</span></a></div>
<div class="layout">${navigation}
<main id="resume">${body}</main></div>
<footer><a href="#intro">Back to top ↑</a><a href="/resume-pdf/">View the PDF version</a></footer></body></html>\n`;
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const target = path.join(root, 'output/web/resume/index.html');
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, await generateWeb());
  console.log('Generated output/web/resume/index.html from resume_source.md.');
}
